-- Generated by scripts/generate-demo-users.mjs — do not edit hashes by hand.

-- Demo credentials (change or remove before production use):

--   admin@theloop.dev / Admin123!  (admin)

--   executive@theloop.dev / Executive123!  (executive)

--   gm@theloop.dev / General123!  (gm)

--   manager@theloop.dev / Manager123!  (manager)

--   chen@theloop.dev / Chef123!  (chef)



INSERT INTO users (name, email, password_hash, title, role_id, is_active)
VALUES ('Alex Admin', 'admin@theloop.dev', 'pbkdf2$100000$e5a4eeb8b2833ce1e792d0b4eac60d58$b6c6f0c647b179451aaccc4c03f6c8d11f914aab48ad8d1631a85169cf64abab', 'System Administrator', (SELECT id FROM roles WHERE key = 'admin'), 1);

INSERT INTO users (name, email, password_hash, title, role_id, is_active)
VALUES ('Erin Executive', 'executive@theloop.dev', 'pbkdf2$100000$3f0b9fb1281d440017a5904d5dbdb223$6c4d1b1fa1bc49da93cf6bd651946801e1b69726a9b350e1b74d062df2c21842', 'Chief Executive Officer', (SELECT id FROM roles WHERE key = 'executive'), 1);

INSERT INTO users (name, email, password_hash, title, role_id, is_active)
VALUES ('Gerald Moss', 'gm@theloop.dev', 'pbkdf2$100000$3d6ef70950519e5b53cebbd7ee1e7019$33e76bdb873648b1a3e2df839fe75169c51e76b4a011842af89398b5a055cf19', 'General Manager', (SELECT id FROM roles WHERE key = 'gm'), 1);

INSERT INTO users (name, email, password_hash, title, role_id, is_active)
VALUES ('Maria Santos', 'manager@theloop.dev', 'pbkdf2$100000$c52f0b4fbb62bc56cf839e02ba331244$b0f2cc5632285f7a6dccfebfe7bb5855dcd34313fd703d7a03a0b09e4d053b53', 'Operations Manager', (SELECT id FROM roles WHERE key = 'manager'), 1);

INSERT INTO users (name, email, password_hash, title, role_id, is_active)
VALUES ('Chen', 'chen@theloop.dev', 'pbkdf2$100000$2db4641032642ff0599df0e34e1028f6$beb4bca1bd5ef8990cc90474aad0b6e50995f03bfc330e9e70f06efb0a66fb6b', 'Head Chef — Kitchen', (SELECT id FROM roles WHERE key = 'chef'), 1);
